### ISSUE TITLE
Issue Downloading Stories

### ISSUE THREAD

**Issue by grapefruitguitar** [skyme5/snapchat-dl#21]
Using the latest versions of Python, PiOS, and Snapchat-dl. Happens on other OS's too

### Description

Describe what you were trying to get done: 
Download a story of a public Snapchat user.

Tell us what happened, what went wrong, and what you expected to happen.
It errored out and failed instead of downloading. I also tried a different IP

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.

snapchat-dl publicsnapchatuser
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 704, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 387, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 1045, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0xb5b26f70>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 788, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='story.snapchat.com', port=443): Max retries exceeded with url: /@publicsnapchatuser (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xb5b26f70>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/username/.local/bin/snapchat-dl", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/username/.local/lib/python3.11/site-packages/snapchat_dl/app.py", line 58, in main
    download_users(usernames)
  File "/home/username/.local/lib/python3.11/site-packages/snapchat_dl/app.py", line 53, in download_users
    downlaoder.download(username)
  File "/home/username/.local/lib/python3.11/site-packages/snapchat_dl/snapchat_dl.py", line 93, in download
    stories, snap_user = self._web_fetch_story(username)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/.local/lib/python3.11/site-packages/snapchat_dl/snapchat_dl.py", line 59, in _web_fetch_story
    response = self._api_response(username)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/.local/lib/python3.11/site-packages/snapchat_dl/snapchat_dl.py", line 45, in _api_response
    return requests.get(web_url).text
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='story.snapchat.com', port=443): Max retries exceeded with url: /@publicsnapchatuser (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xb5b26f70>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

**Comment by JaKrIvMa** [comment]
Same issue here 🥲

**Comment by skyme5** [comment]
Should be fixed in `v2.0.0`
